environment:

  matrix:
    - TARGET_ARCH: x86
      CONDA_NPY: 115
      CONDA_INSTALL_LOCN: C:\\Miniconda35
      CONDA_PY: 35

    - TARGET_ARCH: x64
      CONDA_NPY: 115
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
      CONDA_PY: 35

    - TARGET_ARCH: x86
      CONDA_NPY: 115
      CONDA_INSTALL_LOCN: C:\\Miniconda36
      CONDA_PY: 36

    - TARGET_ARCH: x64
      CONDA_NPY: 115
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_PY: 36

    # add 37 architecture run later this week, after appveyor rolls out new image.
    # - TARGET_ARCH: x86
    #   CONDA_NPY: 115
    #   CONDA_INSTALL_LOCN: C:\\Miniconda37
    #   CONDA_PY: 37

    # - TARGET_ARCH: x64
    #   CONDA_NPY: 115
    #   CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
    #   CONDA_PY: 37

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda info
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda
  - cmd: conda create -q -n test-environment python=%PYTHON_VERSION%
  - cmd: activate test-environment
  - cmd: conda install numpy scipy matplotlib shapely pytest
  - cmd: conda install -c conda-forge pytest-mpl
  - cmd: conda list

build: false

test_script:
  - py.test --mpl --mpl-results-path=tests/results

after_test:
  - cmd: pip install twine
  - cmd: python setup.py bdist_wheel

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'

deploy_script:
  - cmd: python .ci/appveyor/anaconda_upload.py
  - cmd: python .ci/appveyor/pypi_upload.py