{% set name = "rivers2stratigraphy" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ data.get('version') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5644f6890f20e1f397efa79939e10f3383d16e0853139d4c116dc90b2edfd9c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - pip
    - python
    - scipy
    - shapely
  run:
    - matplotlib
    - numpy
    - python
    - scipy
    - shapely

test:
  imports:
    - rivers2stratigraphy

about:
  home: https://github.com/amoodie/rivers2stratigraphy
  license: MIT
  license_family: MIT
  license_file: 
  summary: educational activity for teaching how rivers become stratigraphy
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - amoodie
